# version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://bankolejohn:password@db:5432/mydatabase
      - PORT=3000
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: bankolejohn
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: